### PR TITLE
Workflow for running tests and lint

### PR DESCRIPTION
**Pull request by arunvelsriram**

### CODE REVIEW

**Review by dineshba — COMMENTED** [review]
LGTM

**Comment by arunvelsriram** [comment]
please hold on. am adding lint as well

**Comment by arunvelsriram** [comment]
Done. Sample run is available here: https://github.com/arunvelsriram/stevedore/actions/runs/325843330

**Comment by dineshba** [comment]
Does it make sense to have lint as another step instead of another job ? In this way, we can avoid the checkout/installGo steps in both jobs ?

**Comment by arunvelsriram** [comment]
It was taking around 4 mins to complete. Running them as two simultaneous jobs took only 2 mins. Since its only unit tests, I made it parallel to lint.

When running as sequential steps: https://github.com/arunvelsriram/stevedore/actions/runs/325808516

When run as parallel jobs: https://github.com/arunvelsriram/stevedore/actions/runs/325843330

**Comment by dineshba** [comment]
Oh nice... I didn't notice that they are parallel

**Comment by dineshba** [comment]
Fixes #7

**Pull request merged**
