### PR TITLE
Add steps for installation from source in README

### PR DESCRIPTION
**Pull request by prabhu43**
Added section in README to have installation steps for various methods like brew, from source, from binary release, etc..
And this PR adds steps to install from source.

### CODE REVIEW

**Comment by dineshba** [comment]
As we are gonna add multiple ways to install, we cannot have `stevedore --help` images after each section. I feel, `stevedore --help` command is enough to verify. Thoughts ?

**Comment by prabhu43** [comment]
@dineshba 
we can have separate sub section for verify installation and have this image there. 
or i am fine with removing the image as well

**Comment by prabhu43** [comment]
@jskswamy @dineshba I removed the image now, please review it again and merge the PR

**Comment by jskswamy** [comment]
looks good to me @prabhu43 @dineshba we can merge

**Comment by dineshba** [comment]
Merged

**Pull request merged**
