### PR TITLE
Update demo gif with delays and clear screen after logical step

### LINKED ISSUE #3: Update GIF with delays
- Include delay
- Clear screen on command completion

### PR DESCRIPTION
**Pull request by dineshba**
Signed-off-by: Dinesh <dineshudt17@gmail.com>

Fixes #3 

> Note: Size of the gif is 30MB. We should see how quickly it loads in homepage. It loaded pretty fast for me. Please test it once before merging this.

### CODE REVIEW

**Comment by dineshba** [comment]
Instead of gif, can we go with video https://vimeo.com/471676863 ? so that users can pause and see the details

**Comment by arunvelsriram** [comment]
We could also do a overview video with audio. I saw something like that in [sysdig repo](https://github.com/draios/sysdig#what-does-sysdig-do-and-why-should-i-use-it) which was very nice. 

[sysdig video link](https://www.youtube.com/watch?v=UJ4wVrbP-Q8).

**Comment by dineshba** [comment]
I added more delays and added some text which will provide context to the users. Now gif will provide good overview.

Please see the gif and provide your inputs.

**Comment by jskswamy** [comment]
@arunvelsriram we can create a youtube channel and do a voice over video for different use cases

**Pull request merged**
